# Generated by Django 4.2.26 on 2025-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='programa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Programa de Formación'),
        ),
    ]
