# Generated by Django 4.2.26 on 2025-12-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
        ('aprendices', '0002_alter_aprendiz_options_alter_aprendiz_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programas.programa', verbose_name='Programa de Formación'),
        ),
    ]
