# Generated by Django 6.0.3 on 2026-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_alter_aprendiz_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='programa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Programa de Formación'),
        ),
    ]
