# Generated by Django 6.0.3 on 2026-03-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0004_alter_aprendiz_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
