# Generated by Django 4.2.26 on 2025-12-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Programa')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('nivel_formacion', models.CharField(choices=[('AUX', 'Auxiliar'), ('OPE', 'Operario'), ('TEC', 'Técnico'), ('TGL', 'Tecnólogo'), ('ESP', 'Especialización Tecnológica'), ('COM', 'Complementario')], max_length=3, verbose_name='Nivel de Formación')),
                ('modalidad', models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('MIX', 'Mixta')], default='PRE', max_length=3, verbose_name='Modalidad')),
                ('duracion_meses', models.PositiveIntegerField(verbose_name='Duración en Meses')),
                ('duracion_horas', models.PositiveIntegerField(verbose_name='Duración en Horas')),
                ('descripcion', models.TextField(verbose_name='Descripción del Programa')),
                ('competencias', models.TextField(verbose_name='Competencias a Desarrollar')),
                ('perfil_egreso', models.TextField(verbose_name='Perfil de Egreso')),
                ('requisitos_ingreso', models.TextField(verbose_name='Requisitos de Ingreso')),
                ('centro_formacion', models.CharField(max_length=200, verbose_name='Centro de Formación')),
                ('regional', models.CharField(max_length=100, verbose_name='Regional')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('SUS', 'Suspendido'), ('CAN', 'Cancelado')], default='ACT', max_length=3, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creación del Programa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Programa de Formación',
                'verbose_name_plural': 'Programas de Formación',
                'ordering': ['nombre'],
            },
        ),
    ]
